OUTPUT_DIR: "./exp_prw1"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/public/home/G19940018/FeatureGroup/zhangwenxin/GLCNet-main/data/PRW-v16.04.20"
  BATCH_SIZE_TRAIN: 5
  NUM_WORKERS_TRAIN: 5
SOLVER:
  MAX_EPOCHS: 18
  BASE_LR: 0.003
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
